# Generated by Django 4.2.23 on 2025-07-06 10:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page', models.CharField(max_length=255)),
                ('feature', models.CharField(max_length=255)),
                ('storybook_refs', models.JSONField(default=list)),
                ('design_tokens', models.JSONField(default=list)),
                ('forbidden_scopes', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImplementationStrategy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('components_to_create_or_modify', models.JSONField(default=list)),
                ('files_to_touch', models.JSONField(default=list)),
                ('required_storybook_refs', models.JSONField(default=list)),
                ('design_tokens', models.JSONField(default=list)),
                ('estimated_steps', models.JSONField(default=list)),
                ('success_criteria', models.TextField()),
                ('progress_log', models.JSONField(default=list)),
                ('clarification_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.requirement')),
            ],
        ),
    ]
